import { useSession } from "next-auth/react";
import Head from "next/head";

import Header from "~/components/Header";

import { api } from "~/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" min-h-screen bg-slate-900  ">
        <Header />
        <Content />
      </main>
    </>
  );
}

const Content = () => {
  const { data: sessionData } = useSession();

  const { data: topics, refetch: refetchTopics } = api.topic.getAll.useQuery(
    undefined,
    {
      enabled: sessionData?.user !== undefined,
    },
  );

  const createTopic = api.topic.create.useMutation({
    onSuccess: () => {
      void refetchTopics();
    }
  });
  return (
    <div className=" mt-5 grid grid-cols-4 gap-2 ">
      <div className="px-2">
        <input
          type="text"
          placeholder="New Topic"
          className="input input-bordered input-sm w-full h-10 "
          onKeyDown={(e) => {
            if (e.key === "Enter") {
              createTopic.mutate({
                title: e.currentTarget.value,
              });
              e.currentTarget.value = "";
            }
          }}
        />
        <div className="divider"></div>
        <ul className="menu rounded-box w-56  p-2">
          {topics?.map((topic) => (
            <li key={topic.id}>
              <a
                href="#"
                onClick={(evt) => {
                  evt.preventDefault();
                }}
              >
                {topic.title}
              </a>
            </li>
          ))}
        </ul>
      </div>

      <div className="col-span-3"></div>
    </div>
  );
};
